name: build_deploy_gh_pages
on:
  workflow_dispatch 
jobs:   
  job1: 
    permissions:
      contents: read
      pages: write
      id-token: write
    name: call the reusable workflow
    uses: workflows-and-actions/library/.github/workflows/build_deploy.yml@main
